package com.dropdown;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;

public class MultiDrop {
	public static void main(String[] args) throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", System.getProperty("user.dir")+"\\Driver\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("https://adactinhotelapp.com/");
		//WebElement click_here = driver.findElement(By.xpath("//a[@href='index.php']"));
		//click_here.click();
		WebElement name = driver.findElement(By.name("username"));
		name.sendKeys("Harinigs00007");
		Thread.sleep(3000);
		WebElement pass = driver.findElement(By.name("password"));
		pass.sendKeys("12356!");
		Thread.sleep(3000);
		WebElement login = driver.findElement(By.name("login"));
		login.click();
		WebElement location = driver.findElement(By.name("location"));
		Select s =new Select(location);
		s.selectByValue("Los Angeles");
		Thread.sleep(3000);
		WebElement hotel = driver.findElement(By.name("hotels"));
		Select s1 =new Select(hotel);
		s1.selectByValue("Hotel Creek");
		Thread.sleep(3000);
		WebElement room_type = driver.findElement(By.id("room_type"));
		Select s2 =new Select(room_type);
		s2.selectByValue("Standard");
		Thread.sleep(3000);
		WebElement room_nos = driver.findElement(By.id("room_nos"));
		Select s3 =new Select(room_nos);
		s3.selectByValue("7");
		Thread.sleep(3000);
		WebElement adult_room = driver.findElement(By.id("adult_room"));
		Select s4 =new Select(adult_room);
		s4.selectByVisibleText("4 - Four");
		Thread.sleep(3000);
		WebElement search = driver.findElement(By.name("Submit"));
		search.click();
		Thread.sleep(3000);
		WebElement radio_button = driver.findElement(By.id("radiobutton_0"));
		radio_button.click();
		Thread.sleep(3000);
		WebElement cont = driver.findElement(By.id("continue"));
		cont.click();
		Thread.sleep(3000);
		WebElement fname = driver.findElement(By.id("first_name"));
		fname.sendKeys("Harini");
		Thread.sleep(3000);
		WebElement last_name = driver.findElement(By.id("last_name"));
		last_name.sendKeys("Ganesh");
		Thread.sleep(3000);
		WebElement add = driver.findElement(By.id("address"));
		add.sendKeys("15/70,Avalon Creek,Texas");
		Thread.sleep(3000);
		WebElement credit = driver.findElement(By.id("cc_num"));
		credit.sendKeys("1234123412341234");
		Thread.sleep(3000);
		WebElement card_type = driver.findElement(By.id("cc_type"));
		Select s5 =new Select(card_type);
		s5.selectByValue("VISA");
		Thread.sleep(3000);
		WebElement exp = driver.findElement(By.xpath("//select[@name='cc_exp_month']"));
		Select ex =new Select(exp);
		ex.selectByValue("12");
		Thread.sleep(3000);
		WebElement expyr= driver.findElement(By.id("cc_exp_year"));
		Select exy =new Select(expyr);
		exy.selectByValue("2022");
		Thread.sleep(3000);
		WebElement cvv = driver.findElement(By.id("cc_cvv"));
		cvv.sendKeys("789");
		Thread.sleep(3000);
		WebElement booking = driver.findElement(By.id("book_now"));
		booking.click();
		Thread.sleep(3000);
		WebElement signout = driver.findElement(By.xpath("//a[@href='Logout.php']"));
		signout.click();
		Thread.sleep(5000);
		driver.close();
	}

}
